2017-06-23 08:56:48,607;INFO;Takig details from the user
2017-06-23 08:57:29,351;INFO;Takig details from the user
2017-06-23 08:57:32,239;DEBUG;user given details: name:12, id:name12, profit: 12
2017-06-23 08:57:32,324;INFO;Customer details to insert: name:name12, 			id:12,profit:12
2017-06-23 08:57:32,324;ERROR;'psycopg2.extensions.cursor' object is not callable
Traceback (most recent call last):
  File "/home/tcloudost/pythonexamples/batch28_1/socket_programs/application/db_ops.py", line 15, in insert
    self.name,self.profit))
TypeError: 'psycopg2.extensions.cursor' object is not callable
2017-06-23 08:59:15,327;INFO;Takig details from the user
2017-06-23 08:59:19,066;DEBUG;user given details: name:12, id:name12, profit: 12
2017-06-23 08:59:19,153;INFO;Customer details to insert: name:name12, 			id:12,profit:12
2017-06-23 08:59:19,159;ERROR;syntax error at or near "inser"
LINE 1: inser into customer values(12,'name12',12)
        ^
Traceback (most recent call last):
  File "/home/tcloudost/pythonexamples/batch28_1/socket_programs/application/db_ops.py", line 15, in insert
    self.name,self.profit))
ProgrammingError: syntax error at or near "inser"
LINE 1: inser into customer values(12,'name12',12)
        ^

2017-06-23 08:59:50,604;INFO;Takig details from the user
2017-06-23 08:59:53,554;DEBUG;user given details: name:12, id:name12, profit: 12
2017-06-23 08:59:53,637;INFO;Customer details to insert: name:name12, 			id:12,profit:12
2017-06-23 09:01:36,795;INFO;Takig details from the user
2017-06-23 09:01:41,541;DEBUG;user given details: name:12, id:name13, profit: 12
2017-06-23 09:01:41,677;INFO;Customer details to insert: name:name13, 			id:12,profit:12
2017-06-23 09:01:43,790;INFO;Takig details from the user
2017-06-23 09:01:47,686;DEBUG;user given details: name:14, id:name14, profit: 12
2017-06-23 09:01:47,777;INFO;Customer details to insert: name:name14, 			id:14,profit:12
2017-06-23 09:02:00,719;INFO;Takig details from the user
2017-06-23 09:02:03,900;DEBUG;user given details: name:13, id:name13, profit: 12
2017-06-23 09:02:04,000;INFO;Customer details to insert: name:name13, 			id:13,profit:12
2017-06-23 09:03:02,648;INFO;Takig details from the user
2017-06-23 09:03:07,609;DEBUG;user given details: name:12, id:name12, profit: 12
2017-06-23 09:03:07,698;INFO;Customer details to insert: name:name12, 			id:12,profit:12
2017-06-23 09:03:09,565;INFO;Takig details from the user
2017-06-23 09:03:12,980;DEBUG;user given details: name:13, id:name13, profit: 12
2017-06-23 09:03:13,068;INFO;Customer details to insert: name:name13, 			id:13,profit:12
2017-06-23 09:03:14,930;INFO;Takig details from the user
2017-06-23 09:03:18,178;DEBUG;user given details: name:14, id:name14, profit: 12
2017-06-23 09:03:18,268;INFO;Customer details to insert: name:name14, 			id:14,profit:12
2017-06-23 09:20:58,010;INFO;user selected: search
2017-06-23 09:22:26,845;INFO;user selected: search
2017-06-23 09:22:33,383;DEBUG;Query: q
2017-06-23 09:22:33,386;ERROR;syntax error at or near "selct"
LINE 1: selct * from customer where id=12
        ^
Traceback (most recent call last):
  File "/home/tcloudost/pythonexamples/batch28_1/socket_programs/application/db_ops.py", line 40, in browse
    self.cur.execute(q)
ProgrammingError: syntax error at or near "selct"
LINE 1: selct * from customer where id=12
        ^

2017-06-23 09:23:05,176;INFO;user selected: search
2017-06-23 09:23:09,832;DEBUG;Query: q
